apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: arkhe-operator
  namespace: arkhe-system
  labels:
    control-plane: arkhe-operator
spec:
  selector:
    matchLabels:
      control-plane: arkhe-operator
  endpoints:
  - port: metrics
    interval: 15s
