apiVersion: v1
kind: Namespace
metadata:
  name: arkhe-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: arkhe-operator
  namespace: arkhe-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: arkhe-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: arkhe-operator
subjects:
- kind: ServiceAccount
  name: arkhe-operator
  namespace: arkhe-system
