apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: arkhe-operator
rules:
- apiGroups:
  - arkhe.io
  resources:
  - eras
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - arkhe.io
  resources:
  - eras/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - arkhe.io
  resources:
  - tzinors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - arkhe.io
  resources:
  - tzinors/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - arkhe.io
  resources:
  - vercores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - arkhe.io
  resources:
  - vercores/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - arkhe.io
  resources:
  - entropyshields
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - arkhe.io
  resources:
  - entropyshields/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - arkhe.io
  resources:
  - lambdats
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - arkhe.io
  resources:
  - lambdats/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
