// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.28.3
// source: oracle.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ShardService_CreateShard_FullMethodName    = "/arkhe.api.ShardService/CreateShard"
	ShardService_ListShards_FullMethodName     = "/arkhe.api.ShardService/ListShards"
	ShardService_DestroyShard_FullMethodName   = "/arkhe.api.ShardService/DestroyShard"
	ShardService_GetShardStatus_FullMethodName = "/arkhe.api.ShardService/GetShardStatus"
)

// ShardServiceClient is the client API for ShardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShardServiceClient interface {
	CreateShard(ctx context.Context, in *CreateShardRequest, opts ...grpc.CallOption) (*Shard, error)
	ListShards(ctx context.Context, in *ListShardsRequest, opts ...grpc.CallOption) (*ListShardsResponse, error)
	DestroyShard(ctx context.Context, in *DestroyShardRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetShardStatus(ctx context.Context, in *GetShardStatusRequest, opts ...grpc.CallOption) (*ShardStatus, error)
}

type shardServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShardServiceClient(cc grpc.ClientConnInterface) ShardServiceClient {
	return &shardServiceClient{cc}
}

func (c *shardServiceClient) CreateShard(ctx context.Context, in *CreateShardRequest, opts ...grpc.CallOption) (*Shard, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Shard)
	err := c.cc.Invoke(ctx, ShardService_CreateShard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shardServiceClient) ListShards(ctx context.Context, in *ListShardsRequest, opts ...grpc.CallOption) (*ListShardsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListShardsResponse)
	err := c.cc.Invoke(ctx, ShardService_ListShards_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shardServiceClient) DestroyShard(ctx context.Context, in *DestroyShardRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ShardService_DestroyShard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shardServiceClient) GetShardStatus(ctx context.Context, in *GetShardStatusRequest, opts ...grpc.CallOption) (*ShardStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShardStatus)
	err := c.cc.Invoke(ctx, ShardService_GetShardStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShardServiceServer is the server API for ShardService service.
// All implementations must embed UnimplementedShardServiceServer
// for forward compatibility.
type ShardServiceServer interface {
	CreateShard(context.Context, *CreateShardRequest) (*Shard, error)
	ListShards(context.Context, *ListShardsRequest) (*ListShardsResponse, error)
	DestroyShard(context.Context, *DestroyShardRequest) (*emptypb.Empty, error)
	GetShardStatus(context.Context, *GetShardStatusRequest) (*ShardStatus, error)
	mustEmbedUnimplementedShardServiceServer()
}

// UnimplementedShardServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShardServiceServer struct{}

func (UnimplementedShardServiceServer) CreateShard(context.Context, *CreateShardRequest) (*Shard, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateShard not implemented")
}
func (UnimplementedShardServiceServer) ListShards(context.Context, *ListShardsRequest) (*ListShardsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListShards not implemented")
}
func (UnimplementedShardServiceServer) DestroyShard(context.Context, *DestroyShardRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DestroyShard not implemented")
}
func (UnimplementedShardServiceServer) GetShardStatus(context.Context, *GetShardStatusRequest) (*ShardStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetShardStatus not implemented")
}
func (UnimplementedShardServiceServer) mustEmbedUnimplementedShardServiceServer() {}
func (UnimplementedShardServiceServer) testEmbeddedByValue()                      {}

// UnsafeShardServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShardServiceServer will
// result in compilation errors.
type UnsafeShardServiceServer interface {
	mustEmbedUnimplementedShardServiceServer()
}

func RegisterShardServiceServer(s grpc.ServiceRegistrar, srv ShardServiceServer) {
	// If the following call panics, it indicates UnimplementedShardServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShardService_ServiceDesc, srv)
}

func _ShardService_CreateShard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateShardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShardServiceServer).CreateShard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShardService_CreateShard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShardServiceServer).CreateShard(ctx, req.(*CreateShardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShardService_ListShards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListShardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShardServiceServer).ListShards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShardService_ListShards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShardServiceServer).ListShards(ctx, req.(*ListShardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShardService_DestroyShard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyShardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShardServiceServer).DestroyShard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShardService_DestroyShard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShardServiceServer).DestroyShard(ctx, req.(*DestroyShardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShardService_GetShardStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShardStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShardServiceServer).GetShardStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShardService_GetShardStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShardServiceServer).GetShardStatus(ctx, req.(*GetShardStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShardService_ServiceDesc is the grpc.ServiceDesc for ShardService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShardService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "arkhe.api.ShardService",
	HandlerType: (*ShardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateShard",
			Handler:    _ShardService_CreateShard_Handler,
		},
		{
			MethodName: "ListShards",
			Handler:    _ShardService_ListShards_Handler,
		},
		{
			MethodName: "DestroyShard",
			Handler:    _ShardService_DestroyShard_Handler,
		},
		{
			MethodName: "GetShardStatus",
			Handler:    _ShardService_GetShardStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "oracle.proto",
}

const (
	PortalService_QueryRoyalties_FullMethodName  = "/arkhe.api.PortalService/QueryRoyalties"
	PortalService_GetPortalStatus_FullMethodName = "/arkhe.api.PortalService/GetPortalStatus"
)

// PortalServiceClient is the client API for PortalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PortalServiceClient interface {
	QueryRoyalties(ctx context.Context, in *QueryRoyaltiesRequest, opts ...grpc.CallOption) (*QueryRoyaltiesResponse, error)
	GetPortalStatus(ctx context.Context, in *GetPortalStatusRequest, opts ...grpc.CallOption) (*PortalStatus, error)
}

type portalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPortalServiceClient(cc grpc.ClientConnInterface) PortalServiceClient {
	return &portalServiceClient{cc}
}

func (c *portalServiceClient) QueryRoyalties(ctx context.Context, in *QueryRoyaltiesRequest, opts ...grpc.CallOption) (*QueryRoyaltiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryRoyaltiesResponse)
	err := c.cc.Invoke(ctx, PortalService_QueryRoyalties_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portalServiceClient) GetPortalStatus(ctx context.Context, in *GetPortalStatusRequest, opts ...grpc.CallOption) (*PortalStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PortalStatus)
	err := c.cc.Invoke(ctx, PortalService_GetPortalStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PortalServiceServer is the server API for PortalService service.
// All implementations must embed UnimplementedPortalServiceServer
// for forward compatibility.
type PortalServiceServer interface {
	QueryRoyalties(context.Context, *QueryRoyaltiesRequest) (*QueryRoyaltiesResponse, error)
	GetPortalStatus(context.Context, *GetPortalStatusRequest) (*PortalStatus, error)
	mustEmbedUnimplementedPortalServiceServer()
}

// UnimplementedPortalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPortalServiceServer struct{}

func (UnimplementedPortalServiceServer) QueryRoyalties(context.Context, *QueryRoyaltiesRequest) (*QueryRoyaltiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryRoyalties not implemented")
}
func (UnimplementedPortalServiceServer) GetPortalStatus(context.Context, *GetPortalStatusRequest) (*PortalStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPortalStatus not implemented")
}
func (UnimplementedPortalServiceServer) mustEmbedUnimplementedPortalServiceServer() {}
func (UnimplementedPortalServiceServer) testEmbeddedByValue()                       {}

// UnsafePortalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PortalServiceServer will
// result in compilation errors.
type UnsafePortalServiceServer interface {
	mustEmbedUnimplementedPortalServiceServer()
}

func RegisterPortalServiceServer(s grpc.ServiceRegistrar, srv PortalServiceServer) {
	// If the following call panics, it indicates UnimplementedPortalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PortalService_ServiceDesc, srv)
}

func _PortalService_QueryRoyalties_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRoyaltiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortalServiceServer).QueryRoyalties(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortalService_QueryRoyalties_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortalServiceServer).QueryRoyalties(ctx, req.(*QueryRoyaltiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortalService_GetPortalStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPortalStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortalServiceServer).GetPortalStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortalService_GetPortalStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortalServiceServer).GetPortalStatus(ctx, req.(*GetPortalStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PortalService_ServiceDesc is the grpc.ServiceDesc for PortalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PortalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "arkhe.api.PortalService",
	HandlerType: (*PortalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryRoyalties",
			Handler:    _PortalService_QueryRoyalties_Handler,
		},
		{
			MethodName: "GetPortalStatus",
			Handler:    _PortalService_GetPortalStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "oracle.proto",
}
