// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: oracle.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateShardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubstrateId   string                 `protobuf:"bytes,1,opt,name=substrate_id,json=substrateId,proto3" json:"substrate_id,omitempty"`
	Motor         string                 `protobuf:"bytes,2,opt,name=motor,proto3" json:"motor,omitempty"` // "continental-mind", "qart-engine", ...
	Gpu           bool                   `protobuf:"varint,3,opt,name=gpu,proto3" json:"gpu,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShardRequest) Reset() {
	*x = CreateShardRequest{}
	mi := &file_oracle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShardRequest) ProtoMessage() {}

func (x *CreateShardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oracle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShardRequest.ProtoReflect.Descriptor instead.
func (*CreateShardRequest) Descriptor() ([]byte, []int) {
	return file_oracle_proto_rawDescGZIP(), []int{0}
}

func (x *CreateShardRequest) GetSubstrateId() string {
	if x != nil {
		return x.SubstrateId
	}
	return ""
}

func (x *CreateShardRequest) GetMotor() string {
	if x != nil {
		return x.Motor
	}
	return ""
}

func (x *CreateShardRequest) GetGpu() bool {
	if x != nil {
		return x.Gpu
	}
	return false
}

func (x *CreateShardRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type Shard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	SubstrateId   string                 `protobuf:"bytes,2,opt,name=substrate_id,json=substrateId,proto3" json:"substrate_id,omitempty"`
	Motor         string                 `protobuf:"bytes,3,opt,name=motor,proto3" json:"motor,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`     // "provisioning", "running", "dead"
	Endpoint      string                 `protobuf:"bytes,5,opt,name=endpoint,proto3" json:"endpoint,omitempty"` // gRPC endpoint to the shard itself
	Labels        map[string]string      `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shard) Reset() {
	*x = Shard{}
	mi := &file_oracle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shard) ProtoMessage() {}

func (x *Shard) ProtoReflect() protoreflect.Message {
	mi := &file_oracle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shard.ProtoReflect.Descriptor instead.
func (*Shard) Descriptor() ([]byte, []int) {
	return file_oracle_proto_rawDescGZIP(), []int{1}
}

func (x *Shard) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *Shard) GetSubstrateId() string {
	if x != nil {
		return x.SubstrateId
	}
	return ""
}

func (x *Shard) GetMotor() string {
	if x != nil {
		return x.Motor
	}
	return ""
}

func (x *Shard) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Shard) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Shard) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type ListShardsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListShardsRequest) Reset() {
	*x = ListShardsRequest{}
	mi := &file_oracle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListShardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShardsRequest) ProtoMessage() {}

func (x *ListShardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oracle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShardsRequest.ProtoReflect.Descriptor instead.
func (*ListShardsRequest) Descriptor() ([]byte, []int) {
	return file_oracle_proto_rawDescGZIP(), []int{2}
}

type ListShardsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shards        []*Shard               `protobuf:"bytes,1,rep,name=shards,proto3" json:"shards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListShardsResponse) Reset() {
	*x = ListShardsResponse{}
	mi := &file_oracle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListShardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShardsResponse) ProtoMessage() {}

func (x *ListShardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oracle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShardsResponse.ProtoReflect.Descriptor instead.
func (*ListShardsResponse) Descriptor() ([]byte, []int) {
	return file_oracle_proto_rawDescGZIP(), []int{3}
}

func (x *ListShardsResponse) GetShards() []*Shard {
	if x != nil {
		return x.Shards
	}
	return nil
}

type DestroyShardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyShardRequest) Reset() {
	*x = DestroyShardRequest{}
	mi := &file_oracle_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyShardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyShardRequest) ProtoMessage() {}

func (x *DestroyShardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oracle_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyShardRequest.ProtoReflect.Descriptor instead.
func (*DestroyShardRequest) Descriptor() ([]byte, []int) {
	return file_oracle_proto_rawDescGZIP(), []int{4}
}

func (x *DestroyShardRequest) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

type GetShardStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShardStatusRequest) Reset() {
	*x = GetShardStatusRequest{}
	mi := &file_oracle_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShardStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShardStatusRequest) ProtoMessage() {}

func (x *GetShardStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oracle_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShardStatusRequest.ProtoReflect.Descriptor instead.
func (*GetShardStatusRequest) Descriptor() ([]byte, []int) {
	return file_oracle_proto_rawDescGZIP(), []int{5}
}

func (x *GetShardStatusRequest) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

type ShardStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	Coherence     float64                `protobuf:"fixed64,4,opt,name=coherence,proto3" json:"coherence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardStatus) Reset() {
	*x = ShardStatus{}
	mi := &file_oracle_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardStatus) ProtoMessage() {}

func (x *ShardStatus) ProtoReflect() protoreflect.Message {
	mi := &file_oracle_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardStatus.ProtoReflect.Descriptor instead.
func (*ShardStatus) Descriptor() ([]byte, []int) {
	return file_oracle_proto_rawDescGZIP(), []int{6}
}

func (x *ShardStatus) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *ShardStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ShardStatus) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *ShardStatus) GetCoherence() float64 {
	if x != nil {
		return x.Coherence
	}
	return 0
}

type QueryRoyaltiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRoyaltiesRequest) Reset() {
	*x = QueryRoyaltiesRequest{}
	mi := &file_oracle_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRoyaltiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRoyaltiesRequest) ProtoMessage() {}

func (x *QueryRoyaltiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oracle_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRoyaltiesRequest.ProtoReflect.Descriptor instead.
func (*QueryRoyaltiesRequest) Descriptor() ([]byte, []int) {
	return file_oracle_proto_rawDescGZIP(), []int{7}
}

func (x *QueryRoyaltiesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type RoyaltyEventProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetBlockId string                 `protobuf:"bytes,1,opt,name=target_block_id,json=targetBlockId,proto3" json:"target_block_id,omitempty"`
	SourceOrcid   string                 `protobuf:"bytes,2,opt,name=source_orcid,json=sourceOrcid,proto3" json:"source_orcid,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	PixKey        string                 `protobuf:"bytes,4,opt,name=pix_key,json=pixKey,proto3" json:"pix_key,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoyaltyEventProto) Reset() {
	*x = RoyaltyEventProto{}
	mi := &file_oracle_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoyaltyEventProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoyaltyEventProto) ProtoMessage() {}

func (x *RoyaltyEventProto) ProtoReflect() protoreflect.Message {
	mi := &file_oracle_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoyaltyEventProto.ProtoReflect.Descriptor instead.
func (*RoyaltyEventProto) Descriptor() ([]byte, []int) {
	return file_oracle_proto_rawDescGZIP(), []int{8}
}

func (x *RoyaltyEventProto) GetTargetBlockId() string {
	if x != nil {
		return x.TargetBlockId
	}
	return ""
}

func (x *RoyaltyEventProto) GetSourceOrcid() string {
	if x != nil {
		return x.SourceOrcid
	}
	return ""
}

func (x *RoyaltyEventProto) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *RoyaltyEventProto) GetPixKey() string {
	if x != nil {
		return x.PixKey
	}
	return ""
}

func (x *RoyaltyEventProto) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RoyaltyEventProto) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type QueryRoyaltiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Royalties     []*RoyaltyEventProto   `protobuf:"bytes,1,rep,name=royalties,proto3" json:"royalties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRoyaltiesResponse) Reset() {
	*x = QueryRoyaltiesResponse{}
	mi := &file_oracle_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRoyaltiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRoyaltiesResponse) ProtoMessage() {}

func (x *QueryRoyaltiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oracle_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRoyaltiesResponse.ProtoReflect.Descriptor instead.
func (*QueryRoyaltiesResponse) Descriptor() ([]byte, []int) {
	return file_oracle_proto_rawDescGZIP(), []int{9}
}

func (x *QueryRoyaltiesResponse) GetRoyalties() []*RoyaltyEventProto {
	if x != nil {
		return x.Royalties
	}
	return nil
}

type GetPortalStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPortalStatusRequest) Reset() {
	*x = GetPortalStatusRequest{}
	mi := &file_oracle_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPortalStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPortalStatusRequest) ProtoMessage() {}

func (x *GetPortalStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oracle_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPortalStatusRequest.ProtoReflect.Descriptor instead.
func (*GetPortalStatusRequest) Descriptor() ([]byte, []int) {
	return file_oracle_proto_rawDescGZIP(), []int{10}
}

type PortalStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Status         string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	TotalRoyalties int64                  `protobuf:"varint,2,opt,name=total_royalties,json=totalRoyalties,proto3" json:"total_royalties,omitempty"`
	TotalAmountBrl float64                `protobuf:"fixed64,3,opt,name=total_amount_brl,json=totalAmountBrl,proto3" json:"total_amount_brl,omitempty"`
	BridgeStatus   string                 `protobuf:"bytes,4,opt,name=bridge_status,json=bridgeStatus,proto3" json:"bridge_status,omitempty"`
	Coherence      float64                `protobuf:"fixed64,5,opt,name=coherence,proto3" json:"coherence,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PortalStatus) Reset() {
	*x = PortalStatus{}
	mi := &file_oracle_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortalStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortalStatus) ProtoMessage() {}

func (x *PortalStatus) ProtoReflect() protoreflect.Message {
	mi := &file_oracle_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortalStatus.ProtoReflect.Descriptor instead.
func (*PortalStatus) Descriptor() ([]byte, []int) {
	return file_oracle_proto_rawDescGZIP(), []int{11}
}

func (x *PortalStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PortalStatus) GetTotalRoyalties() int64 {
	if x != nil {
		return x.TotalRoyalties
	}
	return 0
}

func (x *PortalStatus) GetTotalAmountBrl() float64 {
	if x != nil {
		return x.TotalAmountBrl
	}
	return 0
}

func (x *PortalStatus) GetBridgeStatus() string {
	if x != nil {
		return x.BridgeStatus
	}
	return ""
}

func (x *PortalStatus) GetCoherence() float64 {
	if x != nil {
		return x.Coherence
	}
	return 0
}

var File_oracle_proto protoreflect.FileDescriptor

const file_oracle_proto_rawDesc = "" +
	"\n" +
	"\foracle.proto\x12\tarkhe.api\x1a\x1bgoogle/protobuf/empty.proto\"\xdd\x01\n" +
	"\x12CreateShardRequest\x12!\n" +
	"\fsubstrate_id\x18\x01 \x01(\tR\vsubstrateId\x12\x14\n" +
	"\x05motor\x18\x02 \x01(\tR\x05motor\x12\x10\n" +
	"\x03gpu\x18\x03 \x01(\bR\x03gpu\x12A\n" +
	"\x06labels\x18\x04 \x03(\v2).arkhe.api.CreateShardRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x80\x02\n" +
	"\x05Shard\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\x12!\n" +
	"\fsubstrate_id\x18\x02 \x01(\tR\vsubstrateId\x12\x14\n" +
	"\x05motor\x18\x03 \x01(\tR\x05motor\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1a\n" +
	"\bendpoint\x18\x05 \x01(\tR\bendpoint\x124\n" +
	"\x06labels\x18\x06 \x03(\v2\x1c.arkhe.api.Shard.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x13\n" +
	"\x11ListShardsRequest\">\n" +
	"\x12ListShardsResponse\x12(\n" +
	"\x06shards\x18\x01 \x03(\v2\x10.arkhe.api.ShardR\x06shards\"0\n" +
	"\x13DestroyShardRequest\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\"2\n" +
	"\x15GetShardStatusRequest\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\"\x85\x01\n" +
	"\vShardStatus\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x03R\ruptimeSeconds\x12\x1c\n" +
	"\tcoherence\x18\x04 \x01(\x01R\tcoherence\"-\n" +
	"\x15QueryRoyaltiesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"\xc5\x01\n" +
	"\x11RoyaltyEventProto\x12&\n" +
	"\x0ftarget_block_id\x18\x01 \x01(\tR\rtargetBlockId\x12!\n" +
	"\fsource_orcid\x18\x02 \x01(\tR\vsourceOrcid\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x17\n" +
	"\apix_key\x18\x04 \x01(\tR\x06pixKey\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x04R\ttimestamp\"T\n" +
	"\x16QueryRoyaltiesResponse\x12:\n" +
	"\troyalties\x18\x01 \x03(\v2\x1c.arkhe.api.RoyaltyEventProtoR\troyalties\"\x18\n" +
	"\x16GetPortalStatusRequest\"\xbc\x01\n" +
	"\fPortalStatus\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12'\n" +
	"\x0ftotal_royalties\x18\x02 \x01(\x03R\x0etotalRoyalties\x12(\n" +
	"\x10total_amount_brl\x18\x03 \x01(\x01R\x0etotalAmountBrl\x12#\n" +
	"\rbridge_status\x18\x04 \x01(\tR\fbridgeStatus\x12\x1c\n" +
	"\tcoherence\x18\x05 \x01(\x01R\tcoherence2\xad\x02\n" +
	"\fShardService\x12>\n" +
	"\vCreateShard\x12\x1d.arkhe.api.CreateShardRequest\x1a\x10.arkhe.api.Shard\x12I\n" +
	"\n" +
	"ListShards\x12\x1c.arkhe.api.ListShardsRequest\x1a\x1d.arkhe.api.ListShardsResponse\x12F\n" +
	"\fDestroyShard\x12\x1e.arkhe.api.DestroyShardRequest\x1a\x16.google.protobuf.Empty\x12J\n" +
	"\x0eGetShardStatus\x12 .arkhe.api.GetShardStatusRequest\x1a\x16.arkhe.api.ShardStatus2\xb5\x01\n" +
	"\rPortalService\x12U\n" +
	"\x0eQueryRoyalties\x12 .arkhe.api.QueryRoyaltiesRequest\x1a!.arkhe.api.QueryRoyaltiesResponse\x12M\n" +
	"\x0fGetPortalStatus\x12!.arkhe.api.GetPortalStatusRequest\x1a\x17.arkhe.api.PortalStatusB)Z'github.com/arkhe-os/arkhe/cmd/arkhe/apib\x06proto3"

var (
	file_oracle_proto_rawDescOnce sync.Once
	file_oracle_proto_rawDescData []byte
)

func file_oracle_proto_rawDescGZIP() []byte {
	file_oracle_proto_rawDescOnce.Do(func() {
		file_oracle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_oracle_proto_rawDesc), len(file_oracle_proto_rawDesc)))
	})
	return file_oracle_proto_rawDescData
}

var file_oracle_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_oracle_proto_goTypes = []any{
	(*CreateShardRequest)(nil),     // 0: arkhe.api.CreateShardRequest
	(*Shard)(nil),                  // 1: arkhe.api.Shard
	(*ListShardsRequest)(nil),      // 2: arkhe.api.ListShardsRequest
	(*ListShardsResponse)(nil),     // 3: arkhe.api.ListShardsResponse
	(*DestroyShardRequest)(nil),    // 4: arkhe.api.DestroyShardRequest
	(*GetShardStatusRequest)(nil),  // 5: arkhe.api.GetShardStatusRequest
	(*ShardStatus)(nil),            // 6: arkhe.api.ShardStatus
	(*QueryRoyaltiesRequest)(nil),  // 7: arkhe.api.QueryRoyaltiesRequest
	(*RoyaltyEventProto)(nil),      // 8: arkhe.api.RoyaltyEventProto
	(*QueryRoyaltiesResponse)(nil), // 9: arkhe.api.QueryRoyaltiesResponse
	(*GetPortalStatusRequest)(nil), // 10: arkhe.api.GetPortalStatusRequest
	(*PortalStatus)(nil),           // 11: arkhe.api.PortalStatus
	nil,                            // 12: arkhe.api.CreateShardRequest.LabelsEntry
	nil,                            // 13: arkhe.api.Shard.LabelsEntry
	(*emptypb.Empty)(nil),          // 14: google.protobuf.Empty
}
var file_oracle_proto_depIdxs = []int32{
	12, // 0: arkhe.api.CreateShardRequest.labels:type_name -> arkhe.api.CreateShardRequest.LabelsEntry
	13, // 1: arkhe.api.Shard.labels:type_name -> arkhe.api.Shard.LabelsEntry
	1,  // 2: arkhe.api.ListShardsResponse.shards:type_name -> arkhe.api.Shard
	8,  // 3: arkhe.api.QueryRoyaltiesResponse.royalties:type_name -> arkhe.api.RoyaltyEventProto
	0,  // 4: arkhe.api.ShardService.CreateShard:input_type -> arkhe.api.CreateShardRequest
	2,  // 5: arkhe.api.ShardService.ListShards:input_type -> arkhe.api.ListShardsRequest
	4,  // 6: arkhe.api.ShardService.DestroyShard:input_type -> arkhe.api.DestroyShardRequest
	5,  // 7: arkhe.api.ShardService.GetShardStatus:input_type -> arkhe.api.GetShardStatusRequest
	7,  // 8: arkhe.api.PortalService.QueryRoyalties:input_type -> arkhe.api.QueryRoyaltiesRequest
	10, // 9: arkhe.api.PortalService.GetPortalStatus:input_type -> arkhe.api.GetPortalStatusRequest
	1,  // 10: arkhe.api.ShardService.CreateShard:output_type -> arkhe.api.Shard
	3,  // 11: arkhe.api.ShardService.ListShards:output_type -> arkhe.api.ListShardsResponse
	14, // 12: arkhe.api.ShardService.DestroyShard:output_type -> google.protobuf.Empty
	6,  // 13: arkhe.api.ShardService.GetShardStatus:output_type -> arkhe.api.ShardStatus
	9,  // 14: arkhe.api.PortalService.QueryRoyalties:output_type -> arkhe.api.QueryRoyaltiesResponse
	11, // 15: arkhe.api.PortalService.GetPortalStatus:output_type -> arkhe.api.PortalStatus
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_oracle_proto_init() }
func file_oracle_proto_init() {
	if File_oracle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_oracle_proto_rawDesc), len(file_oracle_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_oracle_proto_goTypes,
		DependencyIndexes: file_oracle_proto_depIdxs,
		MessageInfos:      file_oracle_proto_msgTypes,
	}.Build()
	File_oracle_proto = out.File
	file_oracle_proto_goTypes = nil
	file_oracle_proto_depIdxs = nil
}
