//go:build !ignore_autogenerated
// +build !ignore_autogenerated

package v1beta1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

func (in *ThermalEngine) DeepCopyInto(out *ThermalEngine) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *ThermalEngine) DeepCopy() *ThermalEngine {
	if in == nil {
		return nil
	}
	out := new(ThermalEngine)
	in.DeepCopyInto(out)
	return out
}

func (in *ThermalEngineSpec) DeepCopyInto(out *ThermalEngineSpec) {
	*out = *in
	out.HeatSource = in.HeatSource
	out.WorkOutput = in.WorkOutput
	out.Programmability = in.Programmability
	out.CarnotLimit = in.CarnotLimit
}

func (in *ThermalEngineSpec) DeepCopy() *ThermalEngineSpec {
	if in == nil {
		return nil
	}
	out := new(ThermalEngineSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ThermalEngineStatus) DeepCopyInto(out *ThermalEngineStatus) {
	*out = *in
}

func (in *ThermalEngineStatus) DeepCopy() *ThermalEngineStatus {
	if in == nil {
		return nil
	}
	out := new(ThermalEngineStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *ThermalEngineList) DeepCopyInto(out *ThermalEngineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ThermalEngine, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ThermalEngineList) DeepCopy() *ThermalEngineList {
	if in == nil {
		return nil
	}
	out := new(ThermalEngineList)
	in.DeepCopyInto(out)
	return out
}

func (in *ThetaRhythm) DeepCopyInto(out *ThetaRhythm) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *ThetaRhythm) DeepCopy() *ThetaRhythm {
	if in == nil {
		return nil
	}
	out := new(ThetaRhythm)
	in.DeepCopyInto(out)
	return out
}

func (in *ThetaRhythmSpec) DeepCopyInto(out *ThetaRhythmSpec) {
	*out = *in
	out.Target = in.Target
}

func (in *ThetaRhythmSpec) DeepCopy() *ThetaRhythmSpec {
	if in == nil {
		return nil
	}
	out := new(ThetaRhythmSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ThetaRhythmStatus) DeepCopyInto(out *ThetaRhythmStatus) {
	*out = *in
}

func (in *ThetaRhythmStatus) DeepCopy() *ThetaRhythmStatus {
	if in == nil {
		return nil
	}
	out := new(ThetaRhythmStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *ThetaRhythmList) DeepCopyInto(out *ThetaRhythmList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ThetaRhythm, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ThetaRhythmList) DeepCopy() *ThetaRhythmList {
	if in == nil {
		return nil
	}
	out := new(ThetaRhythmList)
	in.DeepCopyInto(out)
	return out
}

func (in *GKPAtom) DeepCopyInto(out *GKPAtom) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *GKPAtom) DeepCopy() *GKPAtom {
	if in == nil {
		return nil
	}
	out := new(GKPAtom)
	in.DeepCopyInto(out)
	return out
}

func (in *GKPAtomSpec) DeepCopyInto(out *GKPAtomSpec) {
	*out = *in
	out.TrapConfiguration = in.TrapConfiguration
	out.GKPEncoding = in.GKPEncoding
	if in.VibrationalModes != nil {
		in, out := &in.VibrationalModes, &out.VibrationalModes
		*out = make([]VibrationalMode, len(*in))
		copy(*out, *in)
	}
}

func (in *GKPAtomSpec) DeepCopy() *GKPAtomSpec {
	if in == nil {
		return nil
	}
	out := new(GKPAtomSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *GKPAtomStatus) DeepCopyInto(out *GKPAtomStatus) {
	*out = *in
	if in.Entanglement != nil {
		in, out := &in.Entanglement, &out.Entanglement
		*out = new(EntanglementStatus)
		**out = **in
	}
}

func (in *GKPAtomStatus) DeepCopy() *GKPAtomStatus {
	if in == nil {
		return nil
	}
	out := new(GKPAtomStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *GKPAtomList) DeepCopyInto(out *GKPAtomList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GKPAtom, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *GKPAtomList) DeepCopy() *GKPAtomList {
	if in == nil {
		return nil
	}
	out := new(GKPAtomList)
	in.DeepCopyInto(out)
	return out
}

func (in *PolaritonBattery) DeepCopyInto(out *PolaritonBattery) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *PolaritonBattery) DeepCopy() *PolaritonBattery {
	if in == nil {
		return nil
	}
	out := new(PolaritonBattery)
	in.DeepCopyInto(out)
	return out
}

func (in *PolaritonBatterySpec) DeepCopyInto(out *PolaritonBatterySpec) {
	*out = *in
	out.Microcavity = in.Microcavity
	out.Charging = in.Charging
	out.Storage = in.Storage
}

func (in *PolaritonBatterySpec) DeepCopy() *PolaritonBatterySpec {
	if in == nil {
		return nil
	}
	out := new(PolaritonBatterySpec)
	in.DeepCopyInto(out)
	return out
}

func (in *PolaritonBatteryStatus) DeepCopyInto(out *PolaritonBatteryStatus) {
	*out = *in
}

func (in *PolaritonBatteryStatus) DeepCopy() *PolaritonBatteryStatus {
	if in == nil {
		return nil
	}
	out := new(PolaritonBatteryStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *PolaritonBatteryList) DeepCopyInto(out *PolaritonBatteryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PolaritonBattery, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *PolaritonBatteryList) DeepCopy() *PolaritonBatteryList {
	if in == nil {
		return nil
	}
	out := new(PolaritonBatteryList)
	in.DeepCopyInto(out)
	return out
}

func (in *IoQTDevice) DeepCopyInto(out *IoQTDevice) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *IoQTDevice) DeepCopy() *IoQTDevice {
	if in == nil {
		return nil
	}
	out := new(IoQTDevice)
	in.DeepCopyInto(out)
	return out
}

func (in *IoQTDeviceSpec) DeepCopyInto(out *IoQTDeviceSpec) {
	*out = *in
	out.QCAConfiguration = in.QCAConfiguration
	if in.ImplantLocation != nil {
		in, out := &in.ImplantLocation, &out.ImplantLocation
		*out = new(Location)
		(*in).DeepCopyInto(*out)
	}
	out.PowerSource = in.PowerSource
}

func (in *IoQTDeviceSpec) DeepCopy() *IoQTDeviceSpec {
	if in == nil {
		return nil
	}
	out := new(IoQTDeviceSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *IoQTDeviceStatus) DeepCopyInto(out *IoQTDeviceStatus) {
	*out = *in
}

func (in *IoQTDeviceStatus) DeepCopy() *IoQTDeviceStatus {
	if in == nil {
		return nil
	}
	out := new(IoQTDeviceStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *IoQTDeviceList) DeepCopyInto(out *IoQTDeviceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IoQTDevice, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *IoQTDeviceList) DeepCopy() *IoQTDeviceList {
	if in == nil {
		return nil
	}
	out := new(IoQTDeviceList)
	in.DeepCopyInto(out)
	return out
}

func (in *QuantumNeuralNetwork) DeepCopyInto(out *QuantumNeuralNetwork) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *QuantumNeuralNetwork) DeepCopy() *QuantumNeuralNetwork {
	if in == nil {
		return nil
	}
	out := new(QuantumNeuralNetwork)
	in.DeepCopyInto(out)
	return out
}

func (in *QuantumNeuralNetworkSpec) DeepCopyInto(out *QuantumNeuralNetworkSpec) {
	*out = *in
	out.Training = in.Training
	if in.HardwareBackend != nil {
		in, out := &in.HardwareBackend, &out.HardwareBackend
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *QuantumNeuralNetworkSpec) DeepCopy() *QuantumNeuralNetworkSpec {
	if in == nil {
		return nil
	}
	out := new(QuantumNeuralNetworkSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *QuantumNeuralNetworkStatus) DeepCopyInto(out *QuantumNeuralNetworkStatus) {
	*out = *in
}

func (in *QuantumNeuralNetworkStatus) DeepCopy() *QuantumNeuralNetworkStatus {
	if in == nil {
		return nil
	}
	out := new(QuantumNeuralNetworkStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *QuantumNeuralNetworkList) DeepCopyInto(out *QuantumNeuralNetworkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]QuantumNeuralNetwork, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *QuantumNeuralNetworkList) DeepCopy() *QuantumNeuralNetworkList {
	if in == nil {
		return nil
	}
	out := new(QuantumNeuralNetworkList)
	in.DeepCopyInto(out)
	return out
}

func (in *PostQuantumCrypto) DeepCopyInto(out *PostQuantumCrypto) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *PostQuantumCrypto) DeepCopy() *PostQuantumCrypto {
	if in == nil {
		return nil
	}
	out := new(PostQuantumCrypto)
	in.DeepCopyInto(out)
	return out
}

func (in *PostQuantumCryptoSpec) DeepCopyInto(out *PostQuantumCryptoSpec) {
	*out = *in
	out.KeyDistribution = in.KeyDistribution
	out.Lattice = in.Lattice
}

func (in *PostQuantumCryptoSpec) DeepCopy() *PostQuantumCryptoSpec {
	if in == nil {
		return nil
	}
	out := new(PostQuantumCryptoSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *PostQuantumCryptoStatus) DeepCopyInto(out *PostQuantumCryptoStatus) {
	*out = *in
}

func (in *PostQuantumCryptoStatus) DeepCopy() *PostQuantumCryptoStatus {
	if in == nil {
		return nil
	}
	out := new(PostQuantumCryptoStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *PostQuantumCryptoList) DeepCopyInto(out *PostQuantumCryptoList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PostQuantumCrypto, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *PostQuantumCryptoList) DeepCopy() *PostQuantumCryptoList {
	if in == nil {
		return nil
	}
	out := new(PostQuantumCryptoList)
	in.DeepCopyInto(out)
	return out
}

func (in *Location) DeepCopyInto(out *Location) {
	*out = *in
	if in.Coordinates != nil {
		in, out := &in.Coordinates, &out.Coordinates
		*out = new(Coordinates)
		**out = **in
	}
}

func (in *Location) DeepCopy() *Location {
	if in == nil {
		return nil
	}
	out := new(Location)
	in.DeepCopyInto(out)
	return out
}

func (in *ProofVerifier) DeepCopyInto(out *ProofVerifier) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *ProofVerifier) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ProofVerifierList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ProofVerifier) DeepCopy() *ProofVerifier {
	if in == nil {
		return nil
	}
	out := new(ProofVerifier)
	in.DeepCopyInto(out)
	return out
}

func (in *ProofVerifierSpec) DeepCopyInto(out *ProofVerifierSpec) {
	*out = *in
	if in.SourceRef != nil {
		in, out := &in.SourceRef, &out.SourceRef
		*out = new(SourceRef)
		(*in).DeepCopyInto(*out)
	}
	if in.Input != nil {
		in, out := &in.Input, &out.Input
		*out = new(ProgramInput)
		**out = **in
	}
	out.ExpectedOutput = in.ExpectedOutput
	if in.VerifierConfig != nil {
		in, out := &in.VerifierConfig, &out.VerifierConfig
		*out = new(VerifierConfig)
		**out = **in
	}
	if in.ChainIntegration != nil {
		in, out := &in.ChainIntegration, &out.ChainIntegration
		*out = new(ChainIntegration)
		**out = **in
	}
	if in.NeuralIntegration != nil {
		in, out := &in.NeuralIntegration, &out.NeuralIntegration
		*out = new(NeuralIntegration)
		**out = **in
	}
}

func (in *ProofVerifierSpec) DeepCopy() *ProofVerifierSpec {
	if in == nil {
		return nil
	}
	out := new(ProofVerifierSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ProofVerifierStatus) DeepCopyInto(out *ProofVerifierStatus) {
	*out = *in
	if in.Proof != nil {
		in, out := &in.Proof, &out.Proof
		*out = new(ProofStatus)
		**out = **in
	}
	if in.ZKCertificate != nil {
		in, out := &in.ZKCertificate, &out.ZKCertificate
		*out = new(ZKCertificateStatus)
		**out = **in
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = new(VerificationMetrics)
		**out = **in
	}
	if in.OnChainRef != nil {
		in, out := &in.OnChainRef, &out.OnChainRef
		*out = new(OnChainRef)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ProofVerifierStatus) DeepCopy() *ProofVerifierStatus {
	if in == nil {
		return nil
	}
	out := new(ProofVerifierStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *ProofVerifierList) DeepCopyInto(out *ProofVerifierList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProofVerifier, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ProofVerifierList) DeepCopy() *ProofVerifierList {
	if in == nil {
		return nil
	}
	out := new(ProofVerifierList)
	in.DeepCopyInto(out)
	return out
}

func (in *SourceRef) DeepCopyInto(out *SourceRef) {
	*out = *in
	if in.ConfigMapRef != nil {
		in, out := &in.ConfigMapRef, &out.ConfigMapRef
		*out = new(ConfigMapRef)
		**out = **in
	}
	if in.GitRef != nil {
		in, out := &in.GitRef, &out.GitRef
		*out = new(GitRef)
		(*in).DeepCopyInto(*out)
	}
}

func (in *SourceRef) DeepCopy() *SourceRef {
	if in == nil {
		return nil
	}
	out := new(SourceRef)
	in.DeepCopyInto(out)
	return out
}

func (in *ConfigMapRef) DeepCopyInto(out *ConfigMapRef) {
	*out = *in
}

func (in *ConfigMapRef) DeepCopy() *ConfigMapRef {
	if in == nil {
		return nil
	}
	out := new(ConfigMapRef)
	in.DeepCopyInto(out)
	return out
}

func (in *GitRef) DeepCopyInto(out *GitRef) {
	*out = *in
}

func (in *GitRef) DeepCopy() *GitRef {
	if in == nil {
		return nil
	}
	out := new(GitRef)
	in.DeepCopyInto(out)
	return out
}

func (in *ProgramInput) DeepCopyInto(out *ProgramInput) {
	*out = *in
}

func (in *ProgramInput) DeepCopy() *ProgramInput {
	if in == nil {
		return nil
	}
	out := new(ProgramInput)
	in.DeepCopyInto(out)
	return out
}

func (in *ExpectedOutput) DeepCopyInto(out *ExpectedOutput) {
	*out = *in
}

func (in *ExpectedOutput) DeepCopy() *ExpectedOutput {
	if in == nil {
		return nil
	}
	out := new(ExpectedOutput)
	in.DeepCopyInto(out)
	return out
}

func (in *VerifierConfig) DeepCopyInto(out *VerifierConfig) {
	*out = *in
}

func (in *VerifierConfig) DeepCopy() *VerifierConfig {
	if in == nil {
		return nil
	}
	out := new(VerifierConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *ChainIntegration) DeepCopyInto(out *ChainIntegration) {
	*out = *in
}

func (in *ChainIntegration) DeepCopy() *ChainIntegration {
	if in == nil {
		return nil
	}
	out := new(ChainIntegration)
	in.DeepCopyInto(out)
	return out
}

func (in *NeuralIntegration) DeepCopyInto(out *NeuralIntegration) {
	*out = *in
}

func (in *NeuralIntegration) DeepCopy() *NeuralIntegration {
	if in == nil {
		return nil
	}
	out := new(NeuralIntegration)
	in.DeepCopyInto(out)
	return out
}

func (in *ProofStatus) DeepCopyInto(out *ProofStatus) {
	*out = *in
}

func (in *ProofStatus) DeepCopy() *ProofStatus {
	if in == nil {
		return nil
	}
	out := new(ProofStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *ZKCertificateStatus) DeepCopyInto(out *ZKCertificateStatus) {
	*out = *in
}

func (in *ZKCertificateStatus) DeepCopy() *ZKCertificateStatus {
	if in == nil {
		return nil
	}
	out := new(ZKCertificateStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *VerificationMetrics) DeepCopyInto(out *VerificationMetrics) {
	*out = *in
}

func (in *VerificationMetrics) DeepCopy() *VerificationMetrics {
	if in == nil {
		return nil
	}
	out := new(VerificationMetrics)
	in.DeepCopyInto(out)
	return out
}

func (in *OnChainRef) DeepCopyInto(out *OnChainRef) {
	*out = *in
}

func (in *OnChainRef) DeepCopy() *OnChainRef {
	if in == nil {
		return nil
	}
	out := new(OnChainRef)
	in.DeepCopyInto(out)
	return out
}

func (in *Condition) DeepCopyInto(out *Condition) {
	*out = *in
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
}

func (in *Condition) DeepCopy() *Condition {
	if in == nil {
		return nil
	}
	out := new(Condition)
	in.DeepCopyInto(out)
	return out
}
